#!/bin/bash
# Helper script to add the SmartCart logo

echo "📦 SmartCart Logo Setup"
echo "======================="
echo ""
echo "To add your logo:"
echo ""
echo "1. Save your logo image as 'smartcart-logo.png'"
echo "2. Move it to: $(pwd)/images/smartcart-logo.png"
echo ""
echo "Or use this command:"
echo "  cp /path/to/your/logo.png $(pwd)/images/smartcart-logo.png"
echo ""
echo "Then commit and push:"
echo "  git add images/smartcart-logo.png"
echo "  git commit -m 'Add SmartCart logo image'"
echo "  git push origin main"
echo ""
echo "The logo should be:"
echo "  - PNG format with transparent background"
echo "  - Approximately 500x500 pixels"
echo "  - Will display at 120x120 in the header"
echo ""
